In [1]:
import numpy as np

In [2]:
# example
mylist = [1, 2, 3]
type(mylist)

list

In [3]:
# to transform to numpy - DOES NOT AFFECT ORRIGINAL
np.array(mylist)

array([1, 2, 3])

In [4]:
myarr = np.array(mylist)
type(myarr)

numpy.ndarray

In [5]:
# matrix creating
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [6]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
# numpy range funciton
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
# step size
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [10]:
# creating arrays with 0 or 1
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [12]:
# making it 2 dimentional
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [13]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [14]:
# returns <start> <stop> <number>, the number is how many we want that are mathematically evenly spaced from each other between 
# <start> and <stop>
np.linspace(0, 10, 3)

array([ 0.,  5., 10.])

In [15]:
# identity matrix, not used just good to know
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

## Random section

In [19]:
# .rand always does under 0 and 1
np.random.rand(1)

array([0.09802109])

In [21]:
np.random.rand(2,2)

array([[0.90167458, 0.26013341],
       [0.58808954, 0.50764076]])

In [22]:
# normal distribution where mean is 0 and STD is 1 (numbers closer to 0 are more likely to get selected)
np.random.randn(3)

array([-0.85185667,  0.22329827, -1.5033271 ])

In [23]:
np.random.randn(2,2)

array([[-0.19438921,  0.28469174],
       [ 1.05151571, -1.20837473]])

In [24]:
# random integers
np.random.randint(0, 100)

12

In [25]:
# can take size
np.random.randint(0, 100, 5)

array([50, 12, 94, 84, 16])

In [26]:
# can take shape
np.random.randint(0, 100, (2, 2))

array([[83, 25],
       [20, 18]])

In [27]:
# using an arbitrary number to lock in random generations to a seed - MUST BE IN THE SAME SELL
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

## Examples and other stuff

In [28]:
arr = np.arange(0, 25)

In [29]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [32]:
# DOES NOT MUTATE - SIZE *MUST* FIT WHOLE DATA SET
arr.reshape(5, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [35]:
# max and min
ranarr = np.random.randint(0, 101, 10)

In [38]:
print(ranarr.max())
print(ranarr.min())

99
2


In [39]:
# to find the index of them
print(ranarr.argmax())
print(ranarr.argmin())

5
7


In [44]:
# data type
ranarr.dtype

dtype('int32')