In [1]:
import numpy as np

In [2]:
arr = np.arange(0, 11)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
# to select a single value, same as regular python
arr[8]

8

In [5]:
arr[1:5]

array([1, 2, 3, 4])

In [6]:
arr[0:5] # same as arr[:5]

array([0, 1, 2, 3, 4])

In [7]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [10]:
# changing multiple values (broadcasting value)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [11]:
arr[0:5] = 100
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [12]:
# reset
arr = np.arange(11)

In [13]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [18]:
# IN NUMPY, THE SLICE OF ARRAY IS A POINTER, NOT A COPY (like JS)
slice_of_arr = arr[:5]
slice_of_arr

array([99, 99, 99, 99, 99])

In [19]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [20]:
slice_of_arr[:] = 99

In [21]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [25]:
# TO AVOID POINTER ISSUES
arr_copy = arr.copy()
arr_copy[:] = 100
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [26]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

# Selection

In [28]:
arr_2d = np.array([[5, 10, 15], [20, 25, 30], [35, 40, 45]])
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [29]:
arr_2d.shape

(3, 3)

In [30]:
arr_2d[0]

array([ 5, 10, 15])

In [31]:
arr_2d[-1]

array([35, 40, 45])

In [34]:
arr_2d[1, 1]
# SAME AS arr_2d[1][1]

25

In [37]:
# can be applied to slicing
# :2 = first 2 rows, 1: = last 2 columns
arr_2d[:2, 1:]

array([[10, 15],
       [25, 30]])

# Conditional selection

In [39]:
arr = np.arange(11)

In [40]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [41]:
arr > 4

array([False, False, False, False, False,  True,  True,  True,  True,
        True,  True])

In [42]:
bool_arr = arr > 4

In [44]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True,  True])

In [45]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [46]:
arr[arr>4]

array([ 5,  6,  7,  8,  9, 10])