In [1]:
import numpy as np

In [3]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
# numpy applies it to each element in the array - DOES NOT MUTATE
arr + 5

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [5]:
arr - 2

array([-2, -1,  0,  1,  2,  3,  4,  5,  6,  7])

In [6]:
# can be done with other arrays (MUST BE SAME SIZE)
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [7]:
arr * arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [8]:
# dividing by 0 doesn't break, but issues warning
arr / arr

C:\Users\rando\anaconda3\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in true_divide
  


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

# all math functions work on arrays too

In [9]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [10]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [11]:
arr.sum()

45

In [13]:
arr.max()

9

In [14]:
arr.std()

2.8722813232690143

# 2 dimentional arrays

In [18]:
a2 = np.arange(25).reshape(5,5)

In [19]:
# takes all the numbers
a2.sum()

300

In [21]:
# sum takes an axis parameter - 0 = rows, 1 = columns
# does it ACROSS (across rows = from top to bottom, across columns does left to right)
a2.sum(axis = 0)

array([50, 55, 60, 65, 70])

In [22]:
a2.sum(axis = 1)

array([ 10,  35,  60,  85, 110])